spring:
  main:
    banner-mode: "console" # Set off banner
  datasource:
    url: jdbc:h2:mem:test # H2
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false # Swagger need disable OSIV (Open Session in View)
    defer-datasource-initialization: true # Initialize a Database add from .sql
    #    show-sql: true # Show SQL
    hibernate:
      ddl-auto: create-drop # Set database Schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true # Show SQL
        format_sql: true # Pretty print the SQL
server:
  port: 8080
