---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cloud-configuration-server
  name: cloud-configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cloud-configuration-server
  template:
    metadata:
      labels:
        run: cloud-configuration-server
        visualize: "true"
    spec:
      containers:
        - name: cloud-configuration-server
          image: arthurstrokov/cloud-configuration-server:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
          #            - name: spring.mvc.servlet.path
          #              value: /cloud-configuration-server
          envFrom:
            - configMapRef:
                name: cloud-configuration-server-config
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cloud-configuration-server
  name: cloud-configuration-server
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    run: cloud-configuration-server
  ports:
    - name: cloud-configuration-server-port
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer
  externalIPs:
    - 192.168.59.100
