---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cloud-configuration-server
  name: cloud-configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cloud-configuration-server
  template:
    metadata:
      labels:
        run: cloud-configuration-server
        visualize: "true"
    spec:
      containers:
        - name: cloud-configuration-server
          image: arthurstrokov/cloud-configuration-server:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: spring.mvc.servlet.path
              value: /cloud-configuration-server
            - name: SERVER-PORT
              value: "8888"
            - name: EUREKA-DEFAULT-ZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA-INSTANCE-HOSTNAME
              value: eureka-server
            - name: ZIPKIN-BASE-URL
              value: "http://10.0.2.2:9411"
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cloud-configuration-server
  name: cloud-configuration-server
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    run: cloud-configuration-server
  ports:
    - name: cloud-configuration-server-port
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer
  externalIPs:
    - 192.168.59.100
