spring:
  main:
    banner-mode: off
---
lingvo:
  api:
    key: ${API-KEY}
    srcLang: ${SRC-LANG:1033}
    dstLang: ${DST-LANG:1049}
---
bot:
  name: EnglishWordTranslatorBot
  token: ${BOT-TOKEN}

---
server:
  port: ${SERVER-PORT:8080}
---
logging:
  level:
    root: info
    org.springframework.cloud.config.client: debug
    com:
      gmail:
        arthurstrokov:
          translatorbot:
            gateway:
              TranslatorBotFeignClient: debug
---
feign:
  client:
    config:
      default:
        errorDecoder: com.gmail.arthurstrokov.translatorbot.configuration.RetreiveMessageErrorDecoder
        loggerLevel: basic
---
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
