spring:
  datasource: # Set database properties
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB:jdbc:postgresql://10.0.2.2:5432/resume_storage_project_db} # postgres_database localhost
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000

  jpa:
    open-in-view: false # Swagger need disable OSIV (Open Session in View)
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  zipkin:
    base-url: http://10.0.2.2:9411

  flyway:
    enabled: true
    schemas: public # default
    baseline-on-migrate: true

  devtools:
    remote:
      secret: secret

  application:
    admin:
      enabled: true

  jackson:
    serialization:
      indent-output: true # Set pretty JSON response
---
springdoc:
  swagger-ui:
    path: /swagger
---
server:
  error:
    include-stacktrace: on_param # Remove 'trace' from Response body
---
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "*" ]
      base-path: "/"
      path-mapping:
        prometheus: metrics
#        enable:
#          http_server_requests: true
