spring:
  application:
    name: test-spring-boot-cloud-configuration
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888/
      enabled: true
      failFast: true
