server:
  port: 8888
---
spring:
  main:
    banner-mode: off
  application:
    name: cloud-configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/{application}
  zipkin:
    base-url: http://localhost:9411
  devtools:
    remote:
      secret: secret
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
---
# Конфиг для актуатора, чтобы был доступен по /metrics для прометея
management:
  #  server: # в идеале метрики на отдельный порт
  #    port: 8889
  endpoint:
    prometheus:
      enabled: true
  # Открываем эндпоинты (только прометей) и переопределяем эндпоинт их на /metrics
  endpoints:
    web:
      exposure:
        include: [ "*", "prometheus" ]
      base-path: "/"
      path-mapping:
        prometheus: metrics
#        enable:
#          http_server_requests: true
