server:
  port: 8888
---
spring:
  main:
    banner-mode: off
  application:
    name: cloud-configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/{application}
