server:
  port: ${SERVER-PORT:8888}
---
spring:
  main:
    banner-mode: off
  application:
    name: cloud-configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/{application}
  zipkin:
    enabled: false
    base-url: ${ZIPKIN-BASE-URL:http://localhost:9411}
  devtools:
    remote:
      secret: secret
---
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-DEFAULT-ZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    hostname: ${EUREKA-INSTANCE-HOSTNAME:localhost}
---
# Actuator
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "*", "prometheus" ]
