spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration/{application}

#server: only for local using
#  port: 8888
