spring:
  data:
    mongodb:
      host: 10.0.2.2 # in simple way there is localhost or 10.0.2.2 for using in Virtualbox Minikube Kubernetes instead of localhost
      port: 27017
      database: test
---
logging:
  level:
    org:
      springframework:
        data: info
    root: info
    org.springframework.cloud.config.client: debug
