spring:
  data:
    mongodb:
      host: 10.0.2.2 # for using in Virtualbox Minikube Kubernetes instead of localhost
      port: 27017
      database: test
---
# logging
logging:
  level:
    org:
      springframework:
        data: info
