spring:
  application:
    name: demo-app
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888/ # only for local using
      enabled: true
      failFast: false
