spring:
  application:
    name: demo-app
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'
  cloud:
    config:
#      uri: http://localhost:8888/ only for local using
      uri: https://spring-boot-cloud-config.herokuapp.com
      enabled: true
      failFast: false
